version: '3'

services:
  db:
    image: 'mongo:6.0'
    container_name: 'mongo'
#    env_file:
#      - ./.env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "urbis"
      MONGO_INITDB_ROOT_PASSWORD: "urbis_password"

  app:
    build: './app'
    container_name: 'app'
#    env_file:
#      - ./.env
    ports:
      - 8000:8000
    environment:
      MONGODB_URI: "mongodb://urbis:urbis_password@db:27017/"
      MONGODB_DATABASE: "urbis"
    depends_on:
      - db

  db-express:
    image: 'mongo-express:latest'
    container_name: 'mongo-ui'
    ports:
      - '8080:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "urbis"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "urbis_password"
      ME_CONFIG_MONGODB_URL: "mongodb://urbis:urbis_password@db:27017/"
    depends_on:
      - db